export const validUser = {
  email: "mathis.brangeon@gmail.com",
  password: "123456",
  name: "Mathis",
  surname: "Brangeon",
  token: "123456789",
  life: 2,
  maxLife: 10,
  avatar: "mathis.png",
  time: {
    dayMe: 45,
    dayTo: 60,
  },
  courses: [
    {
      name: "Cours HTML",
      description: "Cours pour apprendre le HTML",
      step: 12,
      finalStep: 48,
      time: 16,
      type: "famous",
    },
    {
      name: "Design CSS",
      description: "Cours pour apprendre le CSS",
      step: 6,
      finalStep: 24,
      time: 8,
      type: "famous",
    },
    {
      name: "Design CSS",
      description: "Cours pour apprendre le CSS",
      step: 6,
      finalStep: 24,
      time: 16,
      type: "new",
    },
    {
      name: "Design CSS",
      description: "Cours pour apprendre le CSS",
      step: 6,
      finalStep: 24,
      type: "famous",
    },
    {
      name: "Design CSS",
      description: "Cours pour apprendre le CSS",
      step: 6,
      finalStep: 24,
      time: 32,
      type: "new",
    },
    {
      name: "Design CSS",
      description: "Cours pour apprendre le CSS",
      step: 6,
      finalStep: 24,
      time: 45,
      type: "new",
    },
  ],
};
