export const validUser = {
  email: "mathis.brangeon@gmail.com",
  password: "123456",
  name: "Mathis",
  surname: "Brangeon",
  token: "123456789",
  life: 2,
  maxLife: 10,
  avatar: "mathis.png",
  time: {
    dayMe: 45,
    dayTo: 60,
  },
  courses: [
    {
      name: "Cours HTML",
      description: "Cours pour apprendre le HTML",
      step: 12,
      finalStep: 48,
      time: 16,
      type: "famous",
    },
    {
      name: "Design CSS",
      description: "Cours pour apprendre le CSS",
      step: 6,
      finalStep: 24,
      time: 8,
      type: "famous",
    },
    {
      name: "Cours JS",
      description: "Cours pour apprendre le JS",
      step: 2,
      finalStep: 12,
      time: 8,
      type: "new",
    },
    {
      name: "POO PHP",
      description: "Cours pour apprendre la POO en PHP",
      step: 6,
      finalStep: 45,
      time: 45,
      type: "famous",
    },
    {
      name: "Listener JS",
      description: "Cours pour apprendre les listeners en JS",
      step: 7,
      finalStep: 10,
      time: 10,
      type: "new",
    },
    {
      name: "Responsive CSS",
      description: "Cours pour apprendre le responsive en CSS",
      step: 12,
      finalStep: 23,
      time: 23,
      type: "new",
    },
  ],
};
